// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void noRegisteredUser() {
    // Test name: noRegisteredUser
    // Step # | name | target | value
    // 1 | open | https://www.greencity.social/#/greenCity | 
    driver.get("https://www.greencity.social/#/greenCity");
    // 2 | setWindowSize | 1440x900 | 
    driver.manage().window().setSize(new Dimension(1440, 900));
    // 3 | click | css=.nav-left-list:nth-child(1) > .url-name | 
    // click on the "Eco News"
    driver.findElement(By.cssSelector(".nav-left-list:nth-child(1) > .url-name")).click();
    // 4 | click | css=.tag-button:nth-child(1) .text | 
    // turn on filter by News
    driver.findElement(By.cssSelector(".tag-button:nth-child(1) .text")).click();
    // 5 | click | xpath=//*[@id="main-content"]//ul[@aria-label="news list"]//h3[text()=" Пластик у ванілін "] | 
    // click on the news "Пластик у ванілін"
    driver.findElement(By.xpath("//*[@id=\"main-content\"]//ul[@aria-label=\"news list\"]//h3[text()=\" Пластик у ванілін \"]")).click();
    // 6 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 7 | click | css=.counter > .wrapper | 
    driver.findElement(By.cssSelector(".counter > .wrapper")).click();
    // 8 | verifyElementPresent | xpath=//*/app-comments-container | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*/app-comments-container"));
      assert(elements.size() > 0);
    }
    // 9 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 10 | verifyElementNotPresent | css=.comment-width | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".comment-width"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void registeredUserPositive() {
    // Test name: registeredUserPositive
    // Step # | name | target | value
    // 1 | open | https://www.greencity.social/#/greenCity | 
    driver.get("https://www.greencity.social/#/greenCity");
    // 2 | setWindowSize | 1440x900 | 
    driver.manage().window().setSize(new Dimension(1440, 900));
    // 3 | click | css=.header_sign-in-link | 
    driver.findElement(By.cssSelector(".header_sign-in-link")).click();
    // 4 | type | id=email | testerforapp2023@gmail.com
    driver.findElement(By.id("email")).sendKeys("testerforapp2023@gmail.com");
    // 5 | type | id=password | nehmys-hipbic-5jadcU
    driver.findElement(By.id("password")).sendKeys("nehmys-hipbic-5jadcU");
    // 6 | click | css=.greenStyle | 
    driver.findElement(By.cssSelector(".greenStyle")).click();
    // 7 | waitForElementPresent | css=.nav-left-list:nth-child(1) > .url-name | 30000
    // wait  "Eco News"
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".nav-left-list:nth-child(1) > .url-name")));
    }
    // 8 | click | css=.nav-left-list:nth-child(1) > .url-name | 
    driver.findElement(By.cssSelector(".nav-left-list:nth-child(1) > .url-name")).click();
    // 9 | click | css=.tag-button:nth-child(1) .text | 
    // turn on filter by News
    driver.findElement(By.cssSelector(".tag-button:nth-child(1) .text")).click();
    // 10 | click | xpath=//*[@id="main-content"]//ul[@aria-label="news list"]//h3[text()=" Пластик у ванілін "] | 
    // click on the news "Пластик у ванілін"
    driver.findElement(By.xpath("//*[@id=\"main-content\"]//ul[@aria-label=\"news list\"]//h3[text()=\" Пластик у ванілін \"]")).click();
    // 11 | waitForElementPresent | xpath=//*[@id="main-content"]/div/app-comments-container//p[text()="Comments"] | 30000
    // wait Commands
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"main-content\"]/div/app-comments-container//p[text()=\"Comments\"]")));
    }
    // 12 | verifyElementPresent | xpath=//*[@id="main-content"]/div/app-comments-container//p[text()="Comments"] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"main-content\"]/div/app-comments-container//p[text()=\"Comments\"]"));
      assert(elements.size() > 0);
    }
    // 13 | storeText | xpath=//*/app-comments-container//p[@class="total-count"] | countText
    vars.put("countText", driver.findElement(By.xpath("//*/app-comments-container//p[@class=\"total-count\"]")).getText());
    // 14 | echo | ${countText} | 
    System.out.println(vars.get("countText").toString());
    // 15 | executeScript | x=${countText}; return x.length-9; | length
    vars.put("length", js.executeScript("x=arguments[0]; return x.length-9;", vars.get("countText")));
    // 16 | echo | ${length} | 
    System.out.println(vars.get("length").toString());
    // 17 | executeScript | cT=${countText}; return cT.split(" comments"); | beforeCount
    vars.put("beforeCount", js.executeScript("cT=arguments[0]; return cT.split(\" comments\");", vars.get("countText")));
    // 18 | echo | ${beforeCount} | 
    System.out.println(vars.get("beforeCount").toString());
    // 19 | type | css=.comment-width | What a good idea!Test
    driver.findElement(By.cssSelector(".comment-width")).sendKeys("What a good idea!Test");
    // 20 | click | css=.primary-global-button | 
    // click on the button "Comment"
    driver.findElement(By.cssSelector(".primary-global-button")).click();
    // 21 | executeScript | expectedCount =parseInt(${beforeCount}) + 1; return expectedCount + " comments"; | expectedTotalCount
    vars.put("expectedTotalCount", js.executeScript("expectedCount =parseInt(arguments[0]) + 1; return expectedCount + \" comments\";", vars.get("beforeCount")));
    // 22 | echo | ${expectedTotalCount} | 
    System.out.println(vars.get("expectedTotalCount").toString());
    // 23 | pause | 3000 | 
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // 24 | verifyText | //*/app-comments-container//p[@class="total-count"] | ${expectedTotalCount}
    assertThat(driver.findElement(By.xpath("//*/app-comments-container//p[@class=\"total-count\"]")).getText(), is("vars.get(\"expectedTotalCount\").toString()"));
    // 25 | executeScript | today = new Date(); var mm =today.toLocaleString('en-us',{month:'short'});  var dd = today.getDate(); var yyyy = today.getFullYear(); return today = mm+" "+dd+", "+yyyy; | currentDate
    vars.put("currentDate", js.executeScript("today = new Date(); var mm =today.toLocaleString(\'en-us\',{month:\'short\'});  var dd = today.getDate(); var yyyy = today.getFullYear(); return today = mm+\" \"+dd+\", \"+yyyy;"));
    // 26 | echo | ${currentDate} | 
    System.out.println(vars.get("currentDate").toString());
    // 27 | storeText | xpath=//*[@id="main-content"]/div/app-comments-container/app-comments-list/div[1]//span[@class="comment-date-month"][text()] | messageDate
    vars.put("messageDate", driver.findElement(By.xpath("//*[@id=\"main-content\"]/div/app-comments-container/app-comments-list/div[1]//span[@class=\"comment-date-month\"][text()]")).getText());
    // 28 | echo | ${messageDate} | 
    System.out.println(vars.get("messageDate").toString());
    // 29 | verifyText | xpath=//*[@id="main-content"]/div/app-comments-container/app-comments-list/div[1]//span[@class="comment-date-month"][text()] | ${currentDate}
    assertThat(driver.findElement(By.xpath("//*[@id=\"main-content\"]/div/app-comments-container/app-comments-list/div[1]//span[@class=\"comment-date-month\"][text()]")).getText(), is("vars.get(\"currentDate\").toString()"));
    // 30 | storeText | css=.body-2 | userName
    vars.put("userName", driver.findElement(By.cssSelector(".body-2")).getText());
    // 31 | verifyText | xpath=//*[@id="main-content"]/div/app-comments-container/app-comments-list/div[1]/div[2]/span[text()] | ${userName}
    assertThat(driver.findElement(By.xpath("//*[@id=\"main-content\"]/div/app-comments-container/app-comments-list/div[1]/div[2]/span[text()]")).getText(), is("vars.get(\"userName\").toString()"));
    // 32 | click | css=.body-2 | 
    driver.findElement(By.cssSelector(".body-2")).click();
    // 33 | click | css=.drop-down-item:nth-child(2) > a | 
    driver.findElement(By.cssSelector(".drop-down-item:nth-child(2) > a")).click();
  }
  @Test
  public void registredUserNegative() {
    // Test name: registredUserNegative
    // Step # | name | target | value
    // 1 | open | https://www.greencity.social/#/greenCity | 
    driver.get("https://www.greencity.social/#/greenCity");
    // 2 | setWindowSize | 1440x900 | 
    driver.manage().window().setSize(new Dimension(1440, 900));
    // 3 | click | css=.header_sign-in-link | 
    driver.findElement(By.cssSelector(".header_sign-in-link")).click();
    // 4 | type | id=email | testerforapp2023@gmail.com
    driver.findElement(By.id("email")).sendKeys("testerforapp2023@gmail.com");
    // 5 | type | id=password | nehmys-hipbic-5jadcU
    driver.findElement(By.id("password")).sendKeys("nehmys-hipbic-5jadcU");
    // 6 | click | css=.greenStyle | 
    driver.findElement(By.cssSelector(".greenStyle")).click();
    // 7 | waitForElementVisible | xpath=//header//a[contains(text(), "Eco news")] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//header//a[contains(text(), \"Eco news\")]")));
    }
    // 8 | click | xpath=//header//a[contains(text(), "Eco news")] | 
    driver.findElement(By.xpath("//header//a[contains(text(), \"Eco news\")]")).click();
    // 9 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 10 | pause | 3000 | 
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // 11 | click | css=.tag-button:nth-child(1) .text | 
    // turn on filter by News
    driver.findElement(By.cssSelector(".tag-button:nth-child(1) .text")).click();
    // 12 | click | xpath=//*[@id="main-content"]//ul[@aria-label="news list"]//h3[text()=" Пластик у ванілін "] | 
    driver.findElement(By.xpath("//*[@id=\"main-content\"]//ul[@aria-label=\"news list\"]//h3[text()=\" Пластик у ванілін \"]")).click();
    // 13 | runScript | window.scrollTo(0,14) | 
    js.executeScript("window.scrollTo(0,14)");
    // 14 | pause | 3000 | 
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // 15 | verifyElementPresent | css=.primary-global-button | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".primary-global-button"));
      assert(elements.size() > 0);
    }
    // 16 | executeScript | return document.querySelector('.primary-global-button').disabled; | startStatusButton
    vars.put("startStatusButton", js.executeScript("return document.querySelector(\'.primary-global-button\').disabled;"));
    // 17 | echo | ${startStatusButton} | 
    System.out.println(vars.get("startStatusButton").toString());
    // 18 | type | css=.comment-width | n
    driver.findElement(By.cssSelector(".comment-width")).sendKeys("n");
    // 19 | storeValue | css=.comment-width | commentText
    vars.put("commentText", driver.findElement(By.cssSelector(".comment-width")).getAttribute("value"));
    // 20 | echo | ${commentText} | 
    System.out.println(vars.get("commentText").toString());
    // 21 | executeScript | return document.querySelector('.primary-global-button').disabled; | buttonDisable
    vars.put("buttonDisable", js.executeScript("return document.querySelector(\'.primary-global-button\').disabled;"));
    // 22 | echo | ${buttonDisable} | 
    System.out.println(vars.get("buttonDisable").toString());
    // 23 | while | ${buttonDisable} != true | buttonDisable
    while ((Boolean) js.executeScript("return (arguments[0] != true)", vars.get("buttonDisable"))) {
      // 24 | store | Чи могли б ви подумати, що з пластикових відходів можна виробляти не лише речі, але й органічні продукти? Науковці з Единбурзького університету вирішили перевірити цю теорію та зрештою придумали, як за допомогою кишкової палички перетворити пластик у ванілін. Йдеться про хімічну сполуку, яка є основним ароматичним компонентом ванілі.   Щоб продемонструвати, як працює їхня технологія, вони взяли пластикові відходи, які зазнали змін внаслідок впливу навколишнього середовища: світла, вологи або тепла і додали до них модифіковані бактерії. За кімнатної температури кишкова паличка перетворила пластик на ванілін, який, як кажуть вчені, навіть придатний для споживання.  Його використовують у харчових продуктах та у косметиці. За прогнозами вчених, до 2025 року попит на ванілін зросте до 59 тисяч тонн. Безпечність цього продукту вчені хочуть перевірити у наступних своїх дослідженнях. | addedText
      vars.put("addedText", "Чи могли б ви подумати, що з пластикових відходів можна виробляти не лише речі, але й органічні продукти? Науковці з Единбурзького університету вирішили перевірити цю теорію та зрештою придумали, як за допомогою кишкової палички перетворити пластик у ванілін. Йдеться про хімічну сполуку, яка є основним ароматичним компонентом ванілі.   Щоб продемонструвати, як працює їхня технологія, вони взяли пластикові відходи, які зазнали змін внаслідок впливу навколишнього середовища: світла, вологи або тепла і додали до них модифіковані бактерії. За кімнатної температури кишкова паличка перетворила пластик на ванілін, який, як кажуть вчені, навіть придатний для споживання.  Його використовують у харчових продуктах та у косметиці. За прогнозами вчених, до 2025 року попит на ванілін зросте до 59 тисяч тонн. Безпечність цього продукту вчені хочуть перевірити у наступних своїх дослідженнях.");
      // 25 | executeScript | newText=${commentText} + ${addedText}; return newText; | commentText
      vars.put("commentText", js.executeScript("newText=arguments[0] + arguments[1]; return newText;", vars.get("commentText"),vars.get("addedText")));
      // 26 | type | css=.comment-width | ${commentText}
      driver.findElement(By.cssSelector(".comment-width")).sendKeys(vars.get("commentText").toString());
      // 27 | echo | ${commentText} | 
      System.out.println(vars.get("commentText").toString());
      // 28 | executeScript | return ${commentText}.split(' ').length; | messageLength
      vars.put("messageLength", js.executeScript("return arguments[0].split(\' \').length;", vars.get("commentText")));
      // 29 | echo | ${messageLength} | 
      System.out.println(vars.get("messageLength").toString());
      // 30 | executeScript | newState = document.querySelector('.primary-global-button').disabled; return ${buttonDisable}=newState; | buttonDisable
      vars.put("buttonDisable", js.executeScript("newState = document.querySelector(\'.primary-global-button\').disabled; return arguments[0]=newState;", vars.get("buttonDisable")));
      // 31 | echo | ${buttonDisable} | 
      System.out.println(vars.get("buttonDisable").toString());
      // 32 | end |  | 
    }
    // 33 | click | css=.body-2 | 
    // click UserName
    driver.findElement(By.cssSelector(".body-2")).click();
    // 34 | click | css=.drop-down-item:nth-child(2) > a | 
    // Log out
    driver.findElement(By.cssSelector(".drop-down-item:nth-child(2) > a")).click();
  }
}
